### ISSUE TITLE
Notify which server has been successfully scaled up/down

### ISSUE THREAD

**Issue by dvalfre** [engineyard/scaley#24]
On version 1.0.0, when a server (or group of them) _fail(s)_ to start/stop the message sent upstream includes the server id (amazon id).
But when the operations _succeeds_, the message doesn't include which server(s) were actioned.  It will be great if the success message also includes it/them.

**Comment by dvalfre** [comment]
Upon looking at the code trying to find out how to implement this, turns out that:
- only `pkg/workflows/scaling_a_group.go` send messages to upstream.
- they send whatever text is assembled by the methods that actually do the work.
- methods `Upscale` and `Downscale` on `pkg/scaler/individual.go` and `pkg/scaler/legion.go` are the only ones that know which servers are being started/stopped
- the aforementioned methods only return text messages upon failure to do the desired operation.

Based on the above, and as I see it, either `Upscale` and `Downscale` return messages upon successful operations, or they are the ones sending messages upstream.  I do favor the first (although nobody asked) even if it means changing behaviors across the workflow components.

@ess will need your input here.

**Comment by ess** [comment]
Added this for the 2.0.0 milestone, but it's totally blocked by the in-progress refactorization that will make things like this *so* much easier to deal with.
