### ISSUE TITLE
Disable locking of a group upon a configuration setting

### ISSUE THREAD

**Issue by dvalfre** [engineyard/scaley#38]
On some cases, customers may want to disable the locking of a group _upon a scaling failure_.  
One of those cases is when scaley is running on environments with a large number of instances, where Chef is known to error out every now and then and the customer is willing to take the risk of repeating the operation.
Since this is a behavior which may not be wanted by everybody, the suggestion is to implement it tied to a config entry 'locking_on_failure' which defaults to 'true'.

**Comment by ess** [comment]
@dvalfre going with "unlock_on_failure" instead. Semantically, we want something that is false by default so we don't have to do silly things.
